spring:
  application:
    name: aichatdat-backend

  r2dbc:
    url: r2dbc:mysql://aichatproject.mysql.database.azure.com/chataidb?
    username: azureuser
    password: Keadat22!
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
logging:
  level:
    io.r2dbc: info
