server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: aichatdat-backend
  rsocket:
    server:
      transport: websocket
      mapping-path: "/rsocket"
      fragment-size: 65536

  codec:
    max-in-memory-size: 50MB


  lifecycle:
    timeout-per-shutdown-phase: 15s

  r2dbc:
    url: r2dbc:mysql://aichatproject.mysql.database.azure.com/test_chataidb?
    username: azureuser
    password: Keadat22!
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10


  flyway:
    url: jdbc:mysql://aichatproject.mysql.database.azure.com/test_chataidb?
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}


logging:
  level:
    '[io.r2dbc]': info


openai:
  api:
    key: ${GPT_API}


# Google API ----
googleai:
  api:
    key: ${GEMINI_API}
gemini:
  baseurl: https://generativelanguage.googleapis.com