# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AIChatBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_16ad397a43c54aa098adbd0c35e3015c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a159055f14b48ab9d89c4733e4a2077 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_16ad397a43c54aa098adbd0c35e3015c }}/intellioptima/aichat-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AIChatBackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_257ba2b0b4704e47b5d4403250ce978f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_16ad397a43c54aa098adbd0c35e3015c }}/intellioptima/aichat-backend:${{ github.sha }}'